-- +goose Up
ALTER TABLE nodes ADD COLUMN hostname TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN arch TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN os TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN kernel TEXT NOT NULL DEFAULT '';
ALTER TABLE nodes ADD COLUMN last_seen_at TEXT;

-- +goose Down
ALTER TABLE nodes DROP COLUMN last_seen_at;
ALTER TABLE nodes DROP COLUMN kernel;
ALTER TABLE nodes DROP COLUMN os;
ALTER TABLE nodes DROP COLUMN arch;
ALTER TABLE nodes DROP COLUMN hostname;
