// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/app.proto

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Replicas      int32                  `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	DesiredState  string                 `protobuf:"bytes,5,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_deployer_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *App) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *App) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *App) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *App) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *App) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *App) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Deployment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason string                 `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_deployer_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deployment) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *Deployment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Deployment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	TargetPort    int32                  `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TlsEnabled    bool                   `protobuf:"varint,6,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_deployer_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Route) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Route) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *Route) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Route) GetTlsEnabled() bool {
	if x != nil {
		return x.TlsEnabled
	}
	return false
}

type DeployAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeployerYaml  string                 `protobuf:"bytes,1,opt,name=deployer_yaml,json=deployerYaml,proto3" json:"deployer_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAppRequest) Reset() {
	*x = DeployAppRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppRequest) ProtoMessage() {}

func (x *DeployAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppRequest.ProtoReflect.Descriptor instead.
func (*DeployAppRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *DeployAppRequest) GetDeployerYaml() string {
	if x != nil {
		return x.DeployerYaml
	}
	return ""
}

type DeployAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Deployment    *Deployment            `protobuf:"bytes,2,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployAppResponse) Reset() {
	*x = DeployAppResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployAppResponse) ProtoMessage() {}

func (x *DeployAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployAppResponse.ProtoReflect.Descriptor instead.
func (*DeployAppResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *DeployAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *DeployAppResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{5}
}

func (x *ListAppsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAppsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*App                 `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{6}
}

func (x *ListAppsResponse) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *ListAppsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type InspectAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectAppRequest) Reset() {
	*x = InspectAppRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectAppRequest) ProtoMessage() {}

func (x *InspectAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectAppRequest.ProtoReflect.Descriptor instead.
func (*InspectAppRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{7}
}

func (x *InspectAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InspectAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Deployments   []*Deployment          `protobuf:"bytes,2,rep,name=deployments,proto3" json:"deployments,omitempty"`
	Routes        []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectAppResponse) Reset() {
	*x = InspectAppResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectAppResponse) ProtoMessage() {}

func (x *InspectAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectAppResponse.ProtoReflect.Descriptor instead.
func (*InspectAppResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{8}
}

func (x *InspectAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *InspectAppResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *InspectAppResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type DeleteAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppRequest) Reset() {
	*x = DeleteAppRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppRequest) ProtoMessage() {}

func (x *DeleteAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppResponse) Reset() {
	*x = DeleteAppResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppResponse) ProtoMessage() {}

func (x *DeleteAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type GetAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppRequest) Reset() {
	*x = GetAppRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppRequest) ProtoMessage() {}

func (x *GetAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppRequest.ProtoReflect.Descriptor instead.
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{11}
}

func (x *GetAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Deployments   []*Deployment          `protobuf:"bytes,2,rep,name=deployments,proto3" json:"deployments,omitempty"`
	Routes        []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppResponse) Reset() {
	*x = GetAppResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppResponse) ProtoMessage() {}

func (x *GetAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppResponse.ProtoReflect.Descriptor instead.
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{12}
}

func (x *GetAppResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *GetAppResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

func (x *GetAppResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type GetAppStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppStatusRequest) Reset() {
	*x = GetAppStatusRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppStatusRequest) ProtoMessage() {}

func (x *GetAppStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAppStatusRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{13}
}

func (x *GetAppStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAppStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	App               *App                   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	LatestDeployment  *Deployment            `protobuf:"bytes,2,opt,name=latest_deployment,json=latestDeployment,proto3" json:"latest_deployment,omitempty"`
	Routes            []*Route               `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	RuntimeStatus     string                 `protobuf:"bytes,4,opt,name=runtime_status,json=runtimeStatus,proto3" json:"runtime_status,omitempty"`
	DesiredReplicas   int32                  `protobuf:"varint,5,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	AvailableReplicas int32                  `protobuf:"varint,6,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	RunningNodes      []string               `protobuf:"bytes,7,rep,name=running_nodes,json=runningNodes,proto3" json:"running_nodes,omitempty"`
	Warnings          []string               `protobuf:"bytes,8,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAppStatusResponse) Reset() {
	*x = GetAppStatusResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppStatusResponse) ProtoMessage() {}

func (x *GetAppStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAppStatusResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{14}
}

func (x *GetAppStatusResponse) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *GetAppStatusResponse) GetLatestDeployment() *Deployment {
	if x != nil {
		return x.LatestDeployment
	}
	return nil
}

func (x *GetAppStatusResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetAppStatusResponse) GetRuntimeStatus() string {
	if x != nil {
		return x.RuntimeStatus
	}
	return ""
}

func (x *GetAppStatusResponse) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *GetAppStatusResponse) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *GetAppStatusResponse) GetRunningNodes() []string {
	if x != nil {
		return x.RunningNodes
	}
	return nil
}

func (x *GetAppStatusResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type GetDeploymentLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,2,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	TailLines     int32                  `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Follow        bool                   `protobuf:"varint,4,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentLogsRequest) Reset() {
	*x = GetDeploymentLogsRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentLogsRequest) ProtoMessage() {}

func (x *GetDeploymentLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentLogsRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentLogsRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeploymentLogsRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *GetDeploymentLogsRequest) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *GetDeploymentLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *GetDeploymentLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type GetDeploymentLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentLogsResponse) Reset() {
	*x = GetDeploymentLogsResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentLogsResponse) ProtoMessage() {}

func (x *GetDeploymentLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentLogsResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentLogsResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeploymentLogsResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{17}
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{18}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type InspectRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRouteRequest) Reset() {
	*x = InspectRouteRequest{}
	mi := &file_deployer_v1_app_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRouteRequest) ProtoMessage() {}

func (x *InspectRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRouteRequest.ProtoReflect.Descriptor instead.
func (*InspectRouteRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{19}
}

func (x *InspectRouteRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type InspectRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRouteResponse) Reset() {
	*x = InspectRouteResponse{}
	mi := &file_deployer_v1_app_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRouteResponse) ProtoMessage() {}

func (x *InspectRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_app_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRouteResponse.ProtoReflect.Descriptor instead.
func (*InspectRouteResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_app_proto_rawDescGZIP(), []int{20}
}

func (x *InspectRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

var File_deployer_v1_app_proto protoreflect.FileDescriptor

const file_deployer_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x15deployer/v1/app.proto\x12\vdeployer.v1\"\xbe\x01\n" +
	"\x03App\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1a\n" +
	"\breplicas\x18\x04 \x01(\x05R\breplicas\x12#\n" +
	"\rdesired_state\x18\x05 \x01(\tR\fdesiredState\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xb0\x01\n" +
	"\n" +
	"Deployment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0efailure_reason\x18\x04 \x01(\tR\rfailureReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xa0\x01\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\x05R\n" +
	"targetPort\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vtls_enabled\x18\x06 \x01(\bR\n" +
	"tlsEnabled\"7\n" +
	"\x10DeployAppRequest\x12#\n" +
	"\rdeployer_yaml\x18\x01 \x01(\tR\fdeployerYaml\"p\n" +
	"\x11DeployAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.deployer.v1.AppR\x03app\x127\n" +
	"\n" +
	"deployment\x18\x02 \x01(\v2\x17.deployer.v1.DeploymentR\n" +
	"deployment\"M\n" +
	"\x0fListAppsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"`\n" +
	"\x10ListAppsResponse\x12$\n" +
	"\x04apps\x18\x01 \x03(\v2\x10.deployer.v1.AppR\x04apps\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"'\n" +
	"\x11InspectAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x9f\x01\n" +
	"\x12InspectAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.deployer.v1.AppR\x03app\x129\n" +
	"\vdeployments\x18\x02 \x03(\v2\x17.deployer.v1.DeploymentR\vdeployments\x12*\n" +
	"\x06routes\x18\x03 \x03(\v2\x12.deployer.v1.RouteR\x06routes\"&\n" +
	"\x10DeleteAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x11DeleteAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.deployer.v1.AppR\x03app\"#\n" +
	"\rGetAppRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x9b\x01\n" +
	"\x0eGetAppResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.deployer.v1.AppR\x03app\x129\n" +
	"\vdeployments\x18\x02 \x03(\v2\x17.deployer.v1.DeploymentR\vdeployments\x12*\n" +
	"\x06routes\x18\x03 \x03(\v2\x12.deployer.v1.RouteR\x06routes\")\n" +
	"\x13GetAppStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xee\x02\n" +
	"\x14GetAppStatusResponse\x12\"\n" +
	"\x03app\x18\x01 \x01(\v2\x10.deployer.v1.AppR\x03app\x12D\n" +
	"\x11latest_deployment\x18\x02 \x01(\v2\x17.deployer.v1.DeploymentR\x10latestDeployment\x12*\n" +
	"\x06routes\x18\x03 \x03(\v2\x12.deployer.v1.RouteR\x06routes\x12%\n" +
	"\x0eruntime_status\x18\x04 \x01(\tR\rruntimeStatus\x12)\n" +
	"\x10desired_replicas\x18\x05 \x01(\x05R\x0fdesiredReplicas\x12-\n" +
	"\x12available_replicas\x18\x06 \x01(\x05R\x11availableReplicas\x12#\n" +
	"\rrunning_nodes\x18\a \x03(\tR\frunningNodes\x12\x1a\n" +
	"\bwarnings\x18\b \x03(\tR\bwarnings\"\x91\x01\n" +
	"\x18GetDeploymentLogsRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12#\n" +
	"\rdeployment_id\x18\x02 \x01(\tR\fdeploymentId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06follow\x18\x04 \x01(\bR\x06follow\"1\n" +
	"\x19GetDeploymentLogsResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"\x13\n" +
	"\x11ListRoutesRequest\"@\n" +
	"\x12ListRoutesResponse\x12*\n" +
	"\x06routes\x18\x01 \x03(\v2\x12.deployer.v1.RouteR\x06routes\"-\n" +
	"\x13InspectRouteRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"@\n" +
	"\x14InspectRouteResponse\x12(\n" +
	"\x05route\x18\x01 \x01(\v2\x12.deployer.v1.RouteR\x05route2\xde\x05\n" +
	"\n" +
	"AppService\x12J\n" +
	"\tDeployApp\x12\x1d.deployer.v1.DeployAppRequest\x1a\x1e.deployer.v1.DeployAppResponse\x12G\n" +
	"\bListApps\x12\x1c.deployer.v1.ListAppsRequest\x1a\x1d.deployer.v1.ListAppsResponse\x12M\n" +
	"\n" +
	"InspectApp\x12\x1e.deployer.v1.InspectAppRequest\x1a\x1f.deployer.v1.InspectAppResponse\x12J\n" +
	"\tDeleteApp\x12\x1d.deployer.v1.DeleteAppRequest\x1a\x1e.deployer.v1.DeleteAppResponse\x12A\n" +
	"\x06GetApp\x12\x1a.deployer.v1.GetAppRequest\x1a\x1b.deployer.v1.GetAppResponse\x12S\n" +
	"\fGetAppStatus\x12 .deployer.v1.GetAppStatusRequest\x1a!.deployer.v1.GetAppStatusResponse\x12d\n" +
	"\x11GetDeploymentLogs\x12%.deployer.v1.GetDeploymentLogsRequest\x1a&.deployer.v1.GetDeploymentLogsResponse0\x01\x12M\n" +
	"\n" +
	"ListRoutes\x12\x1e.deployer.v1.ListRoutesRequest\x1a\x1f.deployer.v1.ListRoutesResponse\x12S\n" +
	"\fInspectRoute\x12 .deployer.v1.InspectRouteRequest\x1a!.deployer.v1.InspectRouteResponseBPZNgithub.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_app_proto_rawDescOnce sync.Once
	file_deployer_v1_app_proto_rawDescData []byte
)

func file_deployer_v1_app_proto_rawDescGZIP() []byte {
	file_deployer_v1_app_proto_rawDescOnce.Do(func() {
		file_deployer_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_app_proto_rawDesc), len(file_deployer_v1_app_proto_rawDesc)))
	})
	return file_deployer_v1_app_proto_rawDescData
}

var file_deployer_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_deployer_v1_app_proto_goTypes = []any{
	(*App)(nil),                       // 0: deployer.v1.App
	(*Deployment)(nil),                // 1: deployer.v1.Deployment
	(*Route)(nil),                     // 2: deployer.v1.Route
	(*DeployAppRequest)(nil),          // 3: deployer.v1.DeployAppRequest
	(*DeployAppResponse)(nil),         // 4: deployer.v1.DeployAppResponse
	(*ListAppsRequest)(nil),           // 5: deployer.v1.ListAppsRequest
	(*ListAppsResponse)(nil),          // 6: deployer.v1.ListAppsResponse
	(*InspectAppRequest)(nil),         // 7: deployer.v1.InspectAppRequest
	(*InspectAppResponse)(nil),        // 8: deployer.v1.InspectAppResponse
	(*DeleteAppRequest)(nil),          // 9: deployer.v1.DeleteAppRequest
	(*DeleteAppResponse)(nil),         // 10: deployer.v1.DeleteAppResponse
	(*GetAppRequest)(nil),             // 11: deployer.v1.GetAppRequest
	(*GetAppResponse)(nil),            // 12: deployer.v1.GetAppResponse
	(*GetAppStatusRequest)(nil),       // 13: deployer.v1.GetAppStatusRequest
	(*GetAppStatusResponse)(nil),      // 14: deployer.v1.GetAppStatusResponse
	(*GetDeploymentLogsRequest)(nil),  // 15: deployer.v1.GetDeploymentLogsRequest
	(*GetDeploymentLogsResponse)(nil), // 16: deployer.v1.GetDeploymentLogsResponse
	(*ListRoutesRequest)(nil),         // 17: deployer.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),        // 18: deployer.v1.ListRoutesResponse
	(*InspectRouteRequest)(nil),       // 19: deployer.v1.InspectRouteRequest
	(*InspectRouteResponse)(nil),      // 20: deployer.v1.InspectRouteResponse
}
var file_deployer_v1_app_proto_depIdxs = []int32{
	0,  // 0: deployer.v1.DeployAppResponse.app:type_name -> deployer.v1.App
	1,  // 1: deployer.v1.DeployAppResponse.deployment:type_name -> deployer.v1.Deployment
	0,  // 2: deployer.v1.ListAppsResponse.apps:type_name -> deployer.v1.App
	0,  // 3: deployer.v1.InspectAppResponse.app:type_name -> deployer.v1.App
	1,  // 4: deployer.v1.InspectAppResponse.deployments:type_name -> deployer.v1.Deployment
	2,  // 5: deployer.v1.InspectAppResponse.routes:type_name -> deployer.v1.Route
	0,  // 6: deployer.v1.DeleteAppResponse.app:type_name -> deployer.v1.App
	0,  // 7: deployer.v1.GetAppResponse.app:type_name -> deployer.v1.App
	1,  // 8: deployer.v1.GetAppResponse.deployments:type_name -> deployer.v1.Deployment
	2,  // 9: deployer.v1.GetAppResponse.routes:type_name -> deployer.v1.Route
	0,  // 10: deployer.v1.GetAppStatusResponse.app:type_name -> deployer.v1.App
	1,  // 11: deployer.v1.GetAppStatusResponse.latest_deployment:type_name -> deployer.v1.Deployment
	2,  // 12: deployer.v1.GetAppStatusResponse.routes:type_name -> deployer.v1.Route
	2,  // 13: deployer.v1.ListRoutesResponse.routes:type_name -> deployer.v1.Route
	2,  // 14: deployer.v1.InspectRouteResponse.route:type_name -> deployer.v1.Route
	3,  // 15: deployer.v1.AppService.DeployApp:input_type -> deployer.v1.DeployAppRequest
	5,  // 16: deployer.v1.AppService.ListApps:input_type -> deployer.v1.ListAppsRequest
	7,  // 17: deployer.v1.AppService.InspectApp:input_type -> deployer.v1.InspectAppRequest
	9,  // 18: deployer.v1.AppService.DeleteApp:input_type -> deployer.v1.DeleteAppRequest
	11, // 19: deployer.v1.AppService.GetApp:input_type -> deployer.v1.GetAppRequest
	13, // 20: deployer.v1.AppService.GetAppStatus:input_type -> deployer.v1.GetAppStatusRequest
	15, // 21: deployer.v1.AppService.GetDeploymentLogs:input_type -> deployer.v1.GetDeploymentLogsRequest
	17, // 22: deployer.v1.AppService.ListRoutes:input_type -> deployer.v1.ListRoutesRequest
	19, // 23: deployer.v1.AppService.InspectRoute:input_type -> deployer.v1.InspectRouteRequest
	4,  // 24: deployer.v1.AppService.DeployApp:output_type -> deployer.v1.DeployAppResponse
	6,  // 25: deployer.v1.AppService.ListApps:output_type -> deployer.v1.ListAppsResponse
	8,  // 26: deployer.v1.AppService.InspectApp:output_type -> deployer.v1.InspectAppResponse
	10, // 27: deployer.v1.AppService.DeleteApp:output_type -> deployer.v1.DeleteAppResponse
	12, // 28: deployer.v1.AppService.GetApp:output_type -> deployer.v1.GetAppResponse
	14, // 29: deployer.v1.AppService.GetAppStatus:output_type -> deployer.v1.GetAppStatusResponse
	16, // 30: deployer.v1.AppService.GetDeploymentLogs:output_type -> deployer.v1.GetDeploymentLogsResponse
	18, // 31: deployer.v1.AppService.ListRoutes:output_type -> deployer.v1.ListRoutesResponse
	20, // 32: deployer.v1.AppService.InspectRoute:output_type -> deployer.v1.InspectRouteResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_deployer_v1_app_proto_init() }
func file_deployer_v1_app_proto_init() {
	if File_deployer_v1_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_app_proto_rawDesc), len(file_deployer_v1_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_v1_app_proto_goTypes,
		DependencyIndexes: file_deployer_v1_app_proto_depIdxs,
		MessageInfos:      file_deployer_v1_app_proto_msgTypes,
	}.Build()
	File_deployer_v1_app_proto = out.File
	file_deployer_v1_app_proto_goTypes = nil
	file_deployer_v1_app_proto_depIdxs = nil
}
