// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/environment.proto

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEnvironmentBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Values        map[string]string      `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentBundleRequest) Reset() {
	*x = CreateEnvironmentBundleRequest{}
	mi := &file_deployer_v1_environment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentBundleRequest) ProtoMessage() {}

func (x *CreateEnvironmentBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_environment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentBundleRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentBundleRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_environment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEnvironmentBundleRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateEnvironmentBundleRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *CreateEnvironmentBundleRequest) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type EnvironmentBundleMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Names         []string               `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentBundleMetadata) Reset() {
	*x = EnvironmentBundleMetadata{}
	mi := &file_deployer_v1_environment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentBundleMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentBundleMetadata) ProtoMessage() {}

func (x *EnvironmentBundleMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_environment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentBundleMetadata.ProtoReflect.Descriptor instead.
func (*EnvironmentBundleMetadata) Descriptor() ([]byte, []int) {
	return file_deployer_v1_environment_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentBundleMetadata) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *EnvironmentBundleMetadata) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *EnvironmentBundleMetadata) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *EnvironmentBundleMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateEnvironmentBundleResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Bundle        *EnvironmentBundleMetadata `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentBundleResponse) Reset() {
	*x = CreateEnvironmentBundleResponse{}
	mi := &file_deployer_v1_environment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentBundleResponse) ProtoMessage() {}

func (x *CreateEnvironmentBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_environment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentBundleResponse.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentBundleResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_environment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEnvironmentBundleResponse) GetBundle() *EnvironmentBundleMetadata {
	if x != nil {
		return x.Bundle
	}
	return nil
}

var File_deployer_v1_environment_proto protoreflect.FileDescriptor

const file_deployer_v1_environment_proto_rawDesc = "" +
	"\n" +
	"\x1ddeployer/v1/environment.proto\x12\vdeployer.v1\"\xe3\x01\n" +
	"\x1eCreateEnvironmentBundleRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12O\n" +
	"\x06values\x18\x03 \x03(\v27.deployer.v1.CreateEnvironmentBundleRequest.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x19EnvironmentBundleMetadata\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x14\n" +
	"\x05names\x18\x03 \x03(\tR\x05names\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"a\n" +
	"\x1fCreateEnvironmentBundleResponse\x12>\n" +
	"\x06bundle\x18\x01 \x01(\v2&.deployer.v1.EnvironmentBundleMetadataR\x06bundle2\x8a\x01\n" +
	"\x12EnvironmentService\x12t\n" +
	"\x17CreateEnvironmentBundle\x12+.deployer.v1.CreateEnvironmentBundleRequest\x1a,.deployer.v1.CreateEnvironmentBundleResponseBPZNgithub.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_environment_proto_rawDescOnce sync.Once
	file_deployer_v1_environment_proto_rawDescData []byte
)

func file_deployer_v1_environment_proto_rawDescGZIP() []byte {
	file_deployer_v1_environment_proto_rawDescOnce.Do(func() {
		file_deployer_v1_environment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_environment_proto_rawDesc), len(file_deployer_v1_environment_proto_rawDesc)))
	})
	return file_deployer_v1_environment_proto_rawDescData
}

var file_deployer_v1_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_deployer_v1_environment_proto_goTypes = []any{
	(*CreateEnvironmentBundleRequest)(nil),  // 0: deployer.v1.CreateEnvironmentBundleRequest
	(*EnvironmentBundleMetadata)(nil),       // 1: deployer.v1.EnvironmentBundleMetadata
	(*CreateEnvironmentBundleResponse)(nil), // 2: deployer.v1.CreateEnvironmentBundleResponse
	nil,                                     // 3: deployer.v1.CreateEnvironmentBundleRequest.ValuesEntry
}
var file_deployer_v1_environment_proto_depIdxs = []int32{
	3, // 0: deployer.v1.CreateEnvironmentBundleRequest.values:type_name -> deployer.v1.CreateEnvironmentBundleRequest.ValuesEntry
	1, // 1: deployer.v1.CreateEnvironmentBundleResponse.bundle:type_name -> deployer.v1.EnvironmentBundleMetadata
	0, // 2: deployer.v1.EnvironmentService.CreateEnvironmentBundle:input_type -> deployer.v1.CreateEnvironmentBundleRequest
	2, // 3: deployer.v1.EnvironmentService.CreateEnvironmentBundle:output_type -> deployer.v1.CreateEnvironmentBundleResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_deployer_v1_environment_proto_init() }
func file_deployer_v1_environment_proto_init() {
	if File_deployer_v1_environment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_environment_proto_rawDesc), len(file_deployer_v1_environment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_v1_environment_proto_goTypes,
		DependencyIndexes: file_deployer_v1_environment_proto_depIdxs,
		MessageInfos:      file_deployer_v1_environment_proto_msgTypes,
	}.Build()
	File_deployer_v1_environment_proto = out.File
	file_deployer_v1_environment_proto_goTypes = nil
	file_deployer_v1_environment_proto_depIdxs = nil
}
