// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/event.proto

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	AppId         string                 `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DeploymentId  string                 `protobuf:"bytes,8,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,9,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_deployer_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_deployer_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetDeploymentId() string {
	if x != nil {
		return x.DeploymentId
	}
	return ""
}

func (x *Event) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Since         string                 `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_deployer_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListEventsRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ListEventsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListEventsRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ListEventsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_deployer_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type WatchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Node          string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Since         string                 `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_deployer_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *WatchEventsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *WatchEventsRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WatchEventsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WatchEventsRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *WatchEventsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

type WatchEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsResponse) Reset() {
	*x = WatchEventsResponse{}
	mi := &file_deployer_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsResponse) ProtoMessage() {}

func (x *WatchEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsResponse.ProtoReflect.Descriptor instead.
func (*WatchEventsResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *WatchEventsResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_deployer_v1_event_proto protoreflect.FileDescriptor

const file_deployer_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x17deployer/v1/event.proto\x12\vdeployer.v1\"\xfa\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x15\n" +
	"\x06app_id\x18\x06 \x01(\tR\x05appId\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12#\n" +
	"\rdeployment_id\x18\b \x01(\tR\fdeploymentId\x12#\n" +
	"\rmetadata_json\x18\t \x01(\tR\fmetadataJson\"\x95\x01\n" +
	"\x11ListEventsRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x14\n" +
	"\x05since\x18\x05 \x01(\tR\x05since\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"@\n" +
	"\x12ListEventsResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.deployer.v1.EventR\x06events\"\x80\x01\n" +
	"\x12WatchEventsRequest\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x14\n" +
	"\x05since\x18\x05 \x01(\tR\x05since\"?\n" +
	"\x13WatchEventsResponse\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.deployer.v1.EventR\x05event2\xb1\x01\n" +
	"\fEventService\x12M\n" +
	"\n" +
	"ListEvents\x12\x1e.deployer.v1.ListEventsRequest\x1a\x1f.deployer.v1.ListEventsResponse\x12R\n" +
	"\vWatchEvents\x12\x1f.deployer.v1.WatchEventsRequest\x1a .deployer.v1.WatchEventsResponse0\x01BPZNgithub.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_event_proto_rawDescOnce sync.Once
	file_deployer_v1_event_proto_rawDescData []byte
)

func file_deployer_v1_event_proto_rawDescGZIP() []byte {
	file_deployer_v1_event_proto_rawDescOnce.Do(func() {
		file_deployer_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_event_proto_rawDesc), len(file_deployer_v1_event_proto_rawDesc)))
	})
	return file_deployer_v1_event_proto_rawDescData
}

var file_deployer_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_deployer_v1_event_proto_goTypes = []any{
	(*Event)(nil),               // 0: deployer.v1.Event
	(*ListEventsRequest)(nil),   // 1: deployer.v1.ListEventsRequest
	(*ListEventsResponse)(nil),  // 2: deployer.v1.ListEventsResponse
	(*WatchEventsRequest)(nil),  // 3: deployer.v1.WatchEventsRequest
	(*WatchEventsResponse)(nil), // 4: deployer.v1.WatchEventsResponse
}
var file_deployer_v1_event_proto_depIdxs = []int32{
	0, // 0: deployer.v1.ListEventsResponse.events:type_name -> deployer.v1.Event
	0, // 1: deployer.v1.WatchEventsResponse.event:type_name -> deployer.v1.Event
	1, // 2: deployer.v1.EventService.ListEvents:input_type -> deployer.v1.ListEventsRequest
	3, // 3: deployer.v1.EventService.WatchEvents:input_type -> deployer.v1.WatchEventsRequest
	2, // 4: deployer.v1.EventService.ListEvents:output_type -> deployer.v1.ListEventsResponse
	4, // 5: deployer.v1.EventService.WatchEvents:output_type -> deployer.v1.WatchEventsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_deployer_v1_event_proto_init() }
func file_deployer_v1_event_proto_init() {
	if File_deployer_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_event_proto_rawDesc), len(file_deployer_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_v1_event_proto_goTypes,
		DependencyIndexes: file_deployer_v1_event_proto_depIdxs,
		MessageInfos:      file_deployer_v1_event_proto_msgTypes,
	}.Build()
	File_deployer_v1_event_proto = out.File
	file_deployer_v1_event_proto_goTypes = nil
	file_deployer_v1_event_proto_depIdxs = nil
}
