// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/node.proto

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt          string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastSeenAt         string                 `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Hostname           string                 `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch               string                 `protobuf:"bytes,9,opt,name=arch,proto3" json:"arch,omitempty"`
	Os                 string                 `protobuf:"bytes,10,opt,name=os,proto3" json:"os,omitempty"`
	Kernel             string                 `protobuf:"bytes,11,opt,name=kernel,proto3" json:"kernel,omitempty"`
	WireguardIp        string                 `protobuf:"bytes,12,opt,name=wireguard_ip,json=wireguardIp,proto3" json:"wireguard_ip,omitempty"`
	WireguardPublicKey string                 `protobuf:"bytes,13,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	KubernetesStatus   string                 `protobuf:"bytes,14,opt,name=kubernetes_status,json=kubernetesStatus,proto3" json:"kubernetes_status,omitempty"`
	KubernetesMessage  string                 `protobuf:"bytes,15,opt,name=kubernetes_message,json=kubernetesMessage,proto3" json:"kubernetes_message,omitempty"`
	Schedulable        bool                   `protobuf:"varint,16,opt,name=schedulable,proto3" json:"schedulable,omitempty"`
	VpnStatus          string                 `protobuf:"bytes,17,opt,name=vpn_status,json=vpnStatus,proto3" json:"vpn_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_deployer_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Node) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Node) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Node) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Node) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *Node) GetWireguardIp() string {
	if x != nil {
		return x.WireguardIp
	}
	return ""
}

func (x *Node) GetWireguardPublicKey() string {
	if x != nil {
		return x.WireguardPublicKey
	}
	return ""
}

func (x *Node) GetKubernetesStatus() string {
	if x != nil {
		return x.KubernetesStatus
	}
	return ""
}

func (x *Node) GetKubernetesMessage() string {
	if x != nil {
		return x.KubernetesMessage
	}
	return ""
}

func (x *Node) GetSchedulable() bool {
	if x != nil {
		return x.Schedulable
	}
	return false
}

func (x *Node) GetVpnStatus() string {
	if x != nil {
		return x.VpnStatus
	}
	return ""
}

type CreateJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenRequest) Reset() {
	*x = CreateJoinTokenRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenRequest) ProtoMessage() {}

func (x *CreateJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJoinTokenRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CreateJoinTokenRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateJoinTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenResponse) Reset() {
	*x = CreateJoinTokenResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenResponse) ProtoMessage() {}

func (x *CreateJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJoinTokenResponse) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *CreateJoinTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreateJoinTokenResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type JoinNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNodeRequest) Reset() {
	*x = JoinNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeRequest) ProtoMessage() {}

func (x *JoinNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeRequest.ProtoReflect.Descriptor instead.
func (*JoinNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *JoinNodeRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *JoinNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *JoinNodeRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *JoinNodeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type JoinNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	WireguardIp   string                 `protobuf:"bytes,4,opt,name=wireguard_ip,json=wireguardIp,proto3" json:"wireguard_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNodeResponse) Reset() {
	*x = JoinNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeResponse) ProtoMessage() {}

func (x *JoinNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeResponse.ProtoReflect.Descriptor instead.
func (*JoinNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *JoinNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinNodeResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *JoinNodeResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *JoinNodeResponse) GetWireguardIp() string {
	if x != nil {
		return x.WireguardIp
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNodesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeRequest) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type HeartbeatNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch            string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Os              string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Kernel          string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	ResourceSummary string                 `protobuf:"bytes,6,opt,name=resource_summary,json=resourceSummary,proto3" json:"resource_summary,omitempty"`
	VpnStatus       string                 `protobuf:"bytes,7,opt,name=vpn_status,json=vpnStatus,proto3" json:"vpn_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatNodeRequest) Reset() {
	*x = HeartbeatNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNodeRequest) ProtoMessage() {}

func (x *HeartbeatNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNodeRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatNodeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetResourceSummary() string {
	if x != nil {
		return x.ResourceSummary
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetVpnStatus() string {
	if x != nil {
		return x.VpnStatus
	}
	return ""
}

type HeartbeatNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedAt    string                 `protobuf:"bytes,1,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatNodeResponse) Reset() {
	*x = HeartbeatNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNodeResponse) ProtoMessage() {}

func (x *HeartbeatNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNodeResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatNodeResponse) GetAcceptedAt() string {
	if x != nil {
		return x.AcceptedAt
	}
	return ""
}

type GetWorkerBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerBootstrapRequest) Reset() {
	*x = GetWorkerBootstrapRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerBootstrapRequest) ProtoMessage() {}

func (x *GetWorkerBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerBootstrapRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{11}
}

type GetWorkerBootstrapResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeName              string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	WireguardIp           string                 `protobuf:"bytes,2,opt,name=wireguard_ip,json=wireguardIp,proto3" json:"wireguard_ip,omitempty"`
	WireguardSubnet       string                 `protobuf:"bytes,3,opt,name=wireguard_subnet,json=wireguardSubnet,proto3" json:"wireguard_subnet,omitempty"`
	WireguardHubIp        string                 `protobuf:"bytes,4,opt,name=wireguard_hub_ip,json=wireguardHubIp,proto3" json:"wireguard_hub_ip,omitempty"`
	WireguardHubPublicKey string                 `protobuf:"bytes,5,opt,name=wireguard_hub_public_key,json=wireguardHubPublicKey,proto3" json:"wireguard_hub_public_key,omitempty"`
	WireguardEndpoint     string                 `protobuf:"bytes,6,opt,name=wireguard_endpoint,json=wireguardEndpoint,proto3" json:"wireguard_endpoint,omitempty"`
	K3SUrl                string                 `protobuf:"bytes,7,opt,name=k3s_url,json=k3sUrl,proto3" json:"k3s_url,omitempty"`
	K3SToken              string                 `protobuf:"bytes,8,opt,name=k3s_token,json=k3sToken,proto3" json:"k3s_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetWorkerBootstrapResponse) Reset() {
	*x = GetWorkerBootstrapResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerBootstrapResponse) ProtoMessage() {}

func (x *GetWorkerBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerBootstrapResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *GetWorkerBootstrapResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GetWorkerBootstrapResponse) GetWireguardIp() string {
	if x != nil {
		return x.WireguardIp
	}
	return ""
}

func (x *GetWorkerBootstrapResponse) GetWireguardSubnet() string {
	if x != nil {
		return x.WireguardSubnet
	}
	return ""
}

func (x *GetWorkerBootstrapResponse) GetWireguardHubIp() string {
	if x != nil {
		return x.WireguardHubIp
	}
	return ""
}

func (x *GetWorkerBootstrapResponse) GetWireguardHubPublicKey() string {
	if x != nil {
		return x.WireguardHubPublicKey
	}
	return ""
}

func (x *GetWorkerBootstrapResponse) GetWireguardEndpoint() string {
	if x != nil {
		return x.WireguardEndpoint
	}
	return ""
}

func (x *GetWorkerBootstrapResponse) GetK3SUrl() string {
	if x != nil {
		return x.K3SUrl
	}
	return ""
}

func (x *GetWorkerBootstrapResponse) GetK3SToken() string {
	if x != nil {
		return x.K3SToken
	}
	return ""
}

type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *DrainNodeRequest) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

type DrainNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *DrainNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type UncordonNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonNodeRequest) Reset() {
	*x = UncordonNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonNodeRequest) ProtoMessage() {}

func (x *UncordonNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonNodeRequest.ProtoReflect.Descriptor instead.
func (*UncordonNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *UncordonNodeRequest) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

type UncordonNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UncordonNodeResponse) Reset() {
	*x = UncordonNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UncordonNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UncordonNodeResponse) ProtoMessage() {}

func (x *UncordonNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UncordonNodeResponse.ProtoReflect.Descriptor instead.
func (*UncordonNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{16}
}

func (x *UncordonNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveNodeRequest) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type PurgeNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeNodeRequest) Reset() {
	*x = PurgeNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeNodeRequest) ProtoMessage() {}

func (x *PurgeNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeNodeRequest.ProtoReflect.Descriptor instead.
func (*PurgeNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *PurgeNodeRequest) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

type PurgeNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeNodeResponse) Reset() {
	*x = PurgeNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeNodeResponse) ProtoMessage() {}

func (x *PurgeNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeNodeResponse.ProtoReflect.Descriptor instead.
func (*PurgeNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *PurgeNodeResponse) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

func (x *PurgeNodeResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type RenameNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameNodeRequest) Reset() {
	*x = RenameNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameNodeRequest) ProtoMessage() {}

func (x *RenameNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameNodeRequest.ProtoReflect.Descriptor instead.
func (*RenameNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{21}
}

func (x *RenameNodeRequest) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

func (x *RenameNodeRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameNodeResponse) Reset() {
	*x = RenameNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameNodeResponse) ProtoMessage() {}

func (x *RenameNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameNodeResponse.ProtoReflect.Descriptor instead.
func (*RenameNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{22}
}

func (x *RenameNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_deployer_v1_node_proto protoreflect.FileDescriptor

const file_deployer_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x16deployer/v1/node.proto\x12\vdeployer.v1\"\xde\x04\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x125\n" +
	"\x06labels\x18\x04 \x03(\v2\x1d.deployer.v1.Node.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12 \n" +
	"\flast_seen_at\x18\a \x01(\tR\n" +
	"lastSeenAt\x12\x1a\n" +
	"\bhostname\x18\b \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\t \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\n" +
	" \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\v \x01(\tR\x06kernel\x12!\n" +
	"\fwireguard_ip\x18\f \x01(\tR\vwireguardIp\x120\n" +
	"\x14wireguard_public_key\x18\r \x01(\tR\x12wireguardPublicKey\x12+\n" +
	"\x11kubernetes_status\x18\x0e \x01(\tR\x10kubernetesStatus\x12-\n" +
	"\x12kubernetes_message\x18\x0f \x01(\tR\x11kubernetesMessage\x12 \n" +
	"\vschedulable\x18\x10 \x01(\bR\vschedulable\x12\x1d\n" +
	"\n" +
	"vpn_status\x18\x11 \x01(\tR\tvpnStatus\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\x16CreateJoinTokenRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12G\n" +
	"\x06labels\x18\x02 \x03(\v2/.deployer.v1.CreateJoinTokenRequest.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x17CreateJoinTokenResponse\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\"\x7f\n" +
	"\x0fJoinNodeRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\"\x8c\x01\n" +
	"\x10JoinNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12!\n" +
	"\fwireguard_ip\x18\x04 \x01(\tR\vwireguardIp\"N\n" +
	"\x10ListNodesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"d\n" +
	"\x11ListNodesResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.deployer.v1.NodeR\x05nodes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\x0eGetNodeRequest\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\"8\n" +
	"\x0fGetNodeResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.deployer.v1.NodeR\x04node\"\xd0\x01\n" +
	"\x14HeartbeatNodeRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12)\n" +
	"\x10resource_summary\x18\x06 \x01(\tR\x0fresourceSummary\x12\x1d\n" +
	"\n" +
	"vpn_status\x18\a \x01(\tR\tvpnStatus\"8\n" +
	"\x15HeartbeatNodeResponse\x12\x1f\n" +
	"\vaccepted_at\x18\x01 \x01(\tR\n" +
	"acceptedAt\"\x1b\n" +
	"\x19GetWorkerBootstrapRequest\"\xcf\x02\n" +
	"\x1aGetWorkerBootstrapResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12!\n" +
	"\fwireguard_ip\x18\x02 \x01(\tR\vwireguardIp\x12)\n" +
	"\x10wireguard_subnet\x18\x03 \x01(\tR\x0fwireguardSubnet\x12(\n" +
	"\x10wireguard_hub_ip\x18\x04 \x01(\tR\x0ewireguardHubIp\x127\n" +
	"\x18wireguard_hub_public_key\x18\x05 \x01(\tR\x15wireguardHubPublicKey\x12-\n" +
	"\x12wireguard_endpoint\x18\x06 \x01(\tR\x11wireguardEndpoint\x12\x17\n" +
	"\ak3s_url\x18\a \x01(\tR\x06k3sUrl\x12\x1b\n" +
	"\tk3s_token\x18\b \x01(\tR\bk3sToken\"-\n" +
	"\x10DrainNodeRequest\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\":\n" +
	"\x11DrainNodeResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.deployer.v1.NodeR\x04node\"0\n" +
	"\x13UncordonNodeRequest\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\"=\n" +
	"\x14UncordonNodeResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.deployer.v1.NodeR\x04node\".\n" +
	"\x11RemoveNodeRequest\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\";\n" +
	"\x12RemoveNodeResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.deployer.v1.NodeR\x04node\"-\n" +
	"\x10PurgeNodeRequest\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\"K\n" +
	"\x11PurgeNodeResponse\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"I\n" +
	"\x11RenameNodeRequest\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\";\n" +
	"\x12RenameNodeResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.deployer.v1.NodeR\x04node2\x90\a\n" +
	"\vNodeService\x12\\\n" +
	"\x0fCreateJoinToken\x12#.deployer.v1.CreateJoinTokenRequest\x1a$.deployer.v1.CreateJoinTokenResponse\x12G\n" +
	"\bJoinNode\x12\x1c.deployer.v1.JoinNodeRequest\x1a\x1d.deployer.v1.JoinNodeResponse\x12J\n" +
	"\tListNodes\x12\x1d.deployer.v1.ListNodesRequest\x1a\x1e.deployer.v1.ListNodesResponse\x12D\n" +
	"\aGetNode\x12\x1b.deployer.v1.GetNodeRequest\x1a\x1c.deployer.v1.GetNodeResponse\x12V\n" +
	"\rHeartbeatNode\x12!.deployer.v1.HeartbeatNodeRequest\x1a\".deployer.v1.HeartbeatNodeResponse\x12e\n" +
	"\x12GetWorkerBootstrap\x12&.deployer.v1.GetWorkerBootstrapRequest\x1a'.deployer.v1.GetWorkerBootstrapResponse\x12J\n" +
	"\tDrainNode\x12\x1d.deployer.v1.DrainNodeRequest\x1a\x1e.deployer.v1.DrainNodeResponse\x12S\n" +
	"\fUncordonNode\x12 .deployer.v1.UncordonNodeRequest\x1a!.deployer.v1.UncordonNodeResponse\x12M\n" +
	"\n" +
	"RemoveNode\x12\x1e.deployer.v1.RemoveNodeRequest\x1a\x1f.deployer.v1.RemoveNodeResponse\x12J\n" +
	"\tPurgeNode\x12\x1d.deployer.v1.PurgeNodeRequest\x1a\x1e.deployer.v1.PurgeNodeResponse\x12M\n" +
	"\n" +
	"RenameNode\x12\x1e.deployer.v1.RenameNodeRequest\x1a\x1f.deployer.v1.RenameNodeResponseBPZNgithub.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_node_proto_rawDescOnce sync.Once
	file_deployer_v1_node_proto_rawDescData []byte
)

func file_deployer_v1_node_proto_rawDescGZIP() []byte {
	file_deployer_v1_node_proto_rawDescOnce.Do(func() {
		file_deployer_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_node_proto_rawDesc), len(file_deployer_v1_node_proto_rawDesc)))
	})
	return file_deployer_v1_node_proto_rawDescData
}

var file_deployer_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_deployer_v1_node_proto_goTypes = []any{
	(*Node)(nil),                       // 0: deployer.v1.Node
	(*CreateJoinTokenRequest)(nil),     // 1: deployer.v1.CreateJoinTokenRequest
	(*CreateJoinTokenResponse)(nil),    // 2: deployer.v1.CreateJoinTokenResponse
	(*JoinNodeRequest)(nil),            // 3: deployer.v1.JoinNodeRequest
	(*JoinNodeResponse)(nil),           // 4: deployer.v1.JoinNodeResponse
	(*ListNodesRequest)(nil),           // 5: deployer.v1.ListNodesRequest
	(*ListNodesResponse)(nil),          // 6: deployer.v1.ListNodesResponse
	(*GetNodeRequest)(nil),             // 7: deployer.v1.GetNodeRequest
	(*GetNodeResponse)(nil),            // 8: deployer.v1.GetNodeResponse
	(*HeartbeatNodeRequest)(nil),       // 9: deployer.v1.HeartbeatNodeRequest
	(*HeartbeatNodeResponse)(nil),      // 10: deployer.v1.HeartbeatNodeResponse
	(*GetWorkerBootstrapRequest)(nil),  // 11: deployer.v1.GetWorkerBootstrapRequest
	(*GetWorkerBootstrapResponse)(nil), // 12: deployer.v1.GetWorkerBootstrapResponse
	(*DrainNodeRequest)(nil),           // 13: deployer.v1.DrainNodeRequest
	(*DrainNodeResponse)(nil),          // 14: deployer.v1.DrainNodeResponse
	(*UncordonNodeRequest)(nil),        // 15: deployer.v1.UncordonNodeRequest
	(*UncordonNodeResponse)(nil),       // 16: deployer.v1.UncordonNodeResponse
	(*RemoveNodeRequest)(nil),          // 17: deployer.v1.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),         // 18: deployer.v1.RemoveNodeResponse
	(*PurgeNodeRequest)(nil),           // 19: deployer.v1.PurgeNodeRequest
	(*PurgeNodeResponse)(nil),          // 20: deployer.v1.PurgeNodeResponse
	(*RenameNodeRequest)(nil),          // 21: deployer.v1.RenameNodeRequest
	(*RenameNodeResponse)(nil),         // 22: deployer.v1.RenameNodeResponse
	nil,                                // 23: deployer.v1.Node.LabelsEntry
	nil,                                // 24: deployer.v1.CreateJoinTokenRequest.LabelsEntry
}
var file_deployer_v1_node_proto_depIdxs = []int32{
	23, // 0: deployer.v1.Node.labels:type_name -> deployer.v1.Node.LabelsEntry
	24, // 1: deployer.v1.CreateJoinTokenRequest.labels:type_name -> deployer.v1.CreateJoinTokenRequest.LabelsEntry
	0,  // 2: deployer.v1.ListNodesResponse.nodes:type_name -> deployer.v1.Node
	0,  // 3: deployer.v1.GetNodeResponse.node:type_name -> deployer.v1.Node
	0,  // 4: deployer.v1.DrainNodeResponse.node:type_name -> deployer.v1.Node
	0,  // 5: deployer.v1.UncordonNodeResponse.node:type_name -> deployer.v1.Node
	0,  // 6: deployer.v1.RemoveNodeResponse.node:type_name -> deployer.v1.Node
	0,  // 7: deployer.v1.RenameNodeResponse.node:type_name -> deployer.v1.Node
	1,  // 8: deployer.v1.NodeService.CreateJoinToken:input_type -> deployer.v1.CreateJoinTokenRequest
	3,  // 9: deployer.v1.NodeService.JoinNode:input_type -> deployer.v1.JoinNodeRequest
	5,  // 10: deployer.v1.NodeService.ListNodes:input_type -> deployer.v1.ListNodesRequest
	7,  // 11: deployer.v1.NodeService.GetNode:input_type -> deployer.v1.GetNodeRequest
	9,  // 12: deployer.v1.NodeService.HeartbeatNode:input_type -> deployer.v1.HeartbeatNodeRequest
	11, // 13: deployer.v1.NodeService.GetWorkerBootstrap:input_type -> deployer.v1.GetWorkerBootstrapRequest
	13, // 14: deployer.v1.NodeService.DrainNode:input_type -> deployer.v1.DrainNodeRequest
	15, // 15: deployer.v1.NodeService.UncordonNode:input_type -> deployer.v1.UncordonNodeRequest
	17, // 16: deployer.v1.NodeService.RemoveNode:input_type -> deployer.v1.RemoveNodeRequest
	19, // 17: deployer.v1.NodeService.PurgeNode:input_type -> deployer.v1.PurgeNodeRequest
	21, // 18: deployer.v1.NodeService.RenameNode:input_type -> deployer.v1.RenameNodeRequest
	2,  // 19: deployer.v1.NodeService.CreateJoinToken:output_type -> deployer.v1.CreateJoinTokenResponse
	4,  // 20: deployer.v1.NodeService.JoinNode:output_type -> deployer.v1.JoinNodeResponse
	6,  // 21: deployer.v1.NodeService.ListNodes:output_type -> deployer.v1.ListNodesResponse
	8,  // 22: deployer.v1.NodeService.GetNode:output_type -> deployer.v1.GetNodeResponse
	10, // 23: deployer.v1.NodeService.HeartbeatNode:output_type -> deployer.v1.HeartbeatNodeResponse
	12, // 24: deployer.v1.NodeService.GetWorkerBootstrap:output_type -> deployer.v1.GetWorkerBootstrapResponse
	14, // 25: deployer.v1.NodeService.DrainNode:output_type -> deployer.v1.DrainNodeResponse
	16, // 26: deployer.v1.NodeService.UncordonNode:output_type -> deployer.v1.UncordonNodeResponse
	18, // 27: deployer.v1.NodeService.RemoveNode:output_type -> deployer.v1.RemoveNodeResponse
	20, // 28: deployer.v1.NodeService.PurgeNode:output_type -> deployer.v1.PurgeNodeResponse
	22, // 29: deployer.v1.NodeService.RenameNode:output_type -> deployer.v1.RenameNodeResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_deployer_v1_node_proto_init() }
func file_deployer_v1_node_proto_init() {
	if File_deployer_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_node_proto_rawDesc), len(file_deployer_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_v1_node_proto_goTypes,
		DependencyIndexes: file_deployer_v1_node_proto_depIdxs,
		MessageInfos:      file_deployer_v1_node_proto_msgTypes,
	}.Build()
	File_deployer_v1_node_proto = out.File
	file_deployer_v1_node_proto_goTypes = nil
	file_deployer_v1_node_proto_depIdxs = nil
}
