// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/node.proto

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt          string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastSeenAt         string                 `protobuf:"bytes,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Hostname           string                 `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch               string                 `protobuf:"bytes,9,opt,name=arch,proto3" json:"arch,omitempty"`
	Os                 string                 `protobuf:"bytes,10,opt,name=os,proto3" json:"os,omitempty"`
	Kernel             string                 `protobuf:"bytes,11,opt,name=kernel,proto3" json:"kernel,omitempty"`
	WireguardIp        string                 `protobuf:"bytes,12,opt,name=wireguard_ip,json=wireguardIp,proto3" json:"wireguard_ip,omitempty"`
	WireguardPublicKey string                 `protobuf:"bytes,13,opt,name=wireguard_public_key,json=wireguardPublicKey,proto3" json:"wireguard_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_deployer_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Node) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Node) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Node) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Node) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *Node) GetWireguardIp() string {
	if x != nil {
		return x.WireguardIp
	}
	return ""
}

func (x *Node) GetWireguardPublicKey() string {
	if x != nil {
		return x.WireguardPublicKey
	}
	return ""
}

type CreateJoinTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenRequest) Reset() {
	*x = CreateJoinTokenRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenRequest) ProtoMessage() {}

func (x *CreateJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJoinTokenRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CreateJoinTokenRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateJoinTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenResponse) Reset() {
	*x = CreateJoinTokenResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenResponse) ProtoMessage() {}

func (x *CreateJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJoinTokenResponse) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *CreateJoinTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreateJoinTokenResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type JoinNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	PublicKey     string                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNodeRequest) Reset() {
	*x = JoinNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeRequest) ProtoMessage() {}

func (x *JoinNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeRequest.ProtoReflect.Descriptor instead.
func (*JoinNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *JoinNodeRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *JoinNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *JoinNodeRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *JoinNodeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type JoinNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AgentToken    string                 `protobuf:"bytes,2,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	WireguardIp   string                 `protobuf:"bytes,4,opt,name=wireguard_ip,json=wireguardIp,proto3" json:"wireguard_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinNodeResponse) Reset() {
	*x = JoinNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinNodeResponse) ProtoMessage() {}

func (x *JoinNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinNodeResponse.ProtoReflect.Descriptor instead.
func (*JoinNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *JoinNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinNodeResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *JoinNodeResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *JoinNodeResponse) GetWireguardIp() string {
	if x != nil {
		return x.WireguardIp
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNodesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeRef       string                 `protobuf:"bytes,1,opt,name=node_ref,json=nodeRef,proto3" json:"node_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeRequest) GetNodeRef() string {
	if x != nil {
		return x.NodeRef
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type HeartbeatNodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch            string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Os              string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Kernel          string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	ResourceSummary string                 `protobuf:"bytes,6,opt,name=resource_summary,json=resourceSummary,proto3" json:"resource_summary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatNodeRequest) Reset() {
	*x = HeartbeatNodeRequest{}
	mi := &file_deployer_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNodeRequest) ProtoMessage() {}

func (x *HeartbeatNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNodeRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatNodeRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatNodeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *HeartbeatNodeRequest) GetResourceSummary() string {
	if x != nil {
		return x.ResourceSummary
	}
	return ""
}

type HeartbeatNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedAt    string                 `protobuf:"bytes,1,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatNodeResponse) Reset() {
	*x = HeartbeatNodeResponse{}
	mi := &file_deployer_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNodeResponse) ProtoMessage() {}

func (x *HeartbeatNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNodeResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatNodeResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatNodeResponse) GetAcceptedAt() string {
	if x != nil {
		return x.AcceptedAt
	}
	return ""
}

var File_deployer_v1_node_proto protoreflect.FileDescriptor

const file_deployer_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x16deployer/v1/node.proto\x12\vdeployer.v1\"\xc1\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x125\n" +
	"\x06labels\x18\x04 \x03(\v2\x1d.deployer.v1.Node.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12 \n" +
	"\flast_seen_at\x18\a \x01(\tR\n" +
	"lastSeenAt\x12\x1a\n" +
	"\bhostname\x18\b \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\t \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\n" +
	" \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\v \x01(\tR\x06kernel\x12!\n" +
	"\fwireguard_ip\x18\f \x01(\tR\vwireguardIp\x120\n" +
	"\x14wireguard_public_key\x18\r \x01(\tR\x12wireguardPublicKey\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\x16CreateJoinTokenRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12G\n" +
	"\x06labels\x18\x02 \x03(\v2/.deployer.v1.CreateJoinTokenRequest.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x17CreateJoinTokenResponse\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\"\x7f\n" +
	"\x0fJoinNodeRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\tR\tpublicKey\"\x8c\x01\n" +
	"\x10JoinNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vagent_token\x18\x02 \x01(\tR\n" +
	"agentToken\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12!\n" +
	"\fwireguard_ip\x18\x04 \x01(\tR\vwireguardIp\"N\n" +
	"\x10ListNodesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"d\n" +
	"\x11ListNodesResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.deployer.v1.NodeR\x05nodes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"+\n" +
	"\x0eGetNodeRequest\x12\x19\n" +
	"\bnode_ref\x18\x01 \x01(\tR\anodeRef\"8\n" +
	"\x0fGetNodeResponse\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.deployer.v1.NodeR\x04node\"\xb1\x01\n" +
	"\x14HeartbeatNodeRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12)\n" +
	"\x10resource_summary\x18\x06 \x01(\tR\x0fresourceSummary\"8\n" +
	"\x15HeartbeatNodeResponse\x12\x1f\n" +
	"\vaccepted_at\x18\x01 \x01(\tR\n" +
	"acceptedAt2\x9e\x03\n" +
	"\vNodeService\x12\\\n" +
	"\x0fCreateJoinToken\x12#.deployer.v1.CreateJoinTokenRequest\x1a$.deployer.v1.CreateJoinTokenResponse\x12G\n" +
	"\bJoinNode\x12\x1c.deployer.v1.JoinNodeRequest\x1a\x1d.deployer.v1.JoinNodeResponse\x12J\n" +
	"\tListNodes\x12\x1d.deployer.v1.ListNodesRequest\x1a\x1e.deployer.v1.ListNodesResponse\x12D\n" +
	"\aGetNode\x12\x1b.deployer.v1.GetNodeRequest\x1a\x1c.deployer.v1.GetNodeResponse\x12V\n" +
	"\rHeartbeatNode\x12!.deployer.v1.HeartbeatNodeRequest\x1a\".deployer.v1.HeartbeatNodeResponseBPZNgithub.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_node_proto_rawDescOnce sync.Once
	file_deployer_v1_node_proto_rawDescData []byte
)

func file_deployer_v1_node_proto_rawDescGZIP() []byte {
	file_deployer_v1_node_proto_rawDescOnce.Do(func() {
		file_deployer_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_node_proto_rawDesc), len(file_deployer_v1_node_proto_rawDesc)))
	})
	return file_deployer_v1_node_proto_rawDescData
}

var file_deployer_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_deployer_v1_node_proto_goTypes = []any{
	(*Node)(nil),                    // 0: deployer.v1.Node
	(*CreateJoinTokenRequest)(nil),  // 1: deployer.v1.CreateJoinTokenRequest
	(*CreateJoinTokenResponse)(nil), // 2: deployer.v1.CreateJoinTokenResponse
	(*JoinNodeRequest)(nil),         // 3: deployer.v1.JoinNodeRequest
	(*JoinNodeResponse)(nil),        // 4: deployer.v1.JoinNodeResponse
	(*ListNodesRequest)(nil),        // 5: deployer.v1.ListNodesRequest
	(*ListNodesResponse)(nil),       // 6: deployer.v1.ListNodesResponse
	(*GetNodeRequest)(nil),          // 7: deployer.v1.GetNodeRequest
	(*GetNodeResponse)(nil),         // 8: deployer.v1.GetNodeResponse
	(*HeartbeatNodeRequest)(nil),    // 9: deployer.v1.HeartbeatNodeRequest
	(*HeartbeatNodeResponse)(nil),   // 10: deployer.v1.HeartbeatNodeResponse
	nil,                             // 11: deployer.v1.Node.LabelsEntry
	nil,                             // 12: deployer.v1.CreateJoinTokenRequest.LabelsEntry
}
var file_deployer_v1_node_proto_depIdxs = []int32{
	11, // 0: deployer.v1.Node.labels:type_name -> deployer.v1.Node.LabelsEntry
	12, // 1: deployer.v1.CreateJoinTokenRequest.labels:type_name -> deployer.v1.CreateJoinTokenRequest.LabelsEntry
	0,  // 2: deployer.v1.ListNodesResponse.nodes:type_name -> deployer.v1.Node
	0,  // 3: deployer.v1.GetNodeResponse.node:type_name -> deployer.v1.Node
	1,  // 4: deployer.v1.NodeService.CreateJoinToken:input_type -> deployer.v1.CreateJoinTokenRequest
	3,  // 5: deployer.v1.NodeService.JoinNode:input_type -> deployer.v1.JoinNodeRequest
	5,  // 6: deployer.v1.NodeService.ListNodes:input_type -> deployer.v1.ListNodesRequest
	7,  // 7: deployer.v1.NodeService.GetNode:input_type -> deployer.v1.GetNodeRequest
	9,  // 8: deployer.v1.NodeService.HeartbeatNode:input_type -> deployer.v1.HeartbeatNodeRequest
	2,  // 9: deployer.v1.NodeService.CreateJoinToken:output_type -> deployer.v1.CreateJoinTokenResponse
	4,  // 10: deployer.v1.NodeService.JoinNode:output_type -> deployer.v1.JoinNodeResponse
	6,  // 11: deployer.v1.NodeService.ListNodes:output_type -> deployer.v1.ListNodesResponse
	8,  // 12: deployer.v1.NodeService.GetNode:output_type -> deployer.v1.GetNodeResponse
	10, // 13: deployer.v1.NodeService.HeartbeatNode:output_type -> deployer.v1.HeartbeatNodeResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_deployer_v1_node_proto_init() }
func file_deployer_v1_node_proto_init() {
	if File_deployer_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_node_proto_rawDesc), len(file_deployer_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_v1_node_proto_goTypes,
		DependencyIndexes: file_deployer_v1_node_proto_depIdxs,
		MessageInfos:      file_deployer_v1_node_proto_msgTypes,
	}.Build()
	File_deployer_v1_node_proto = out.File
	file_deployer_v1_node_proto_goTypes = nil
	file_deployer_v1_node_proto_depIdxs = nil
}
