// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/registry.proto

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRegistryCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Registry      string                 `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegistryCredentialRequest) Reset() {
	*x = CreateRegistryCredentialRequest{}
	mi := &file_deployer_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegistryCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegistryCredentialRequest) ProtoMessage() {}

func (x *CreateRegistryCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegistryCredentialRequest.ProtoReflect.Descriptor instead.
func (*CreateRegistryCredentialRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRegistryCredentialRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateRegistryCredentialRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *CreateRegistryCredentialRequest) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *CreateRegistryCredentialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateRegistryCredentialRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegistryCredentialMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Registry      string                 `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryCredentialMetadata) Reset() {
	*x = RegistryCredentialMetadata{}
	mi := &file_deployer_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryCredentialMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryCredentialMetadata) ProtoMessage() {}

func (x *RegistryCredentialMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryCredentialMetadata.ProtoReflect.Descriptor instead.
func (*RegistryCredentialMetadata) Descriptor() ([]byte, []int) {
	return file_deployer_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryCredentialMetadata) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RegistryCredentialMetadata) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *RegistryCredentialMetadata) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *RegistryCredentialMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateRegistryCredentialResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Credential    *RegistryCredentialMetadata `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegistryCredentialResponse) Reset() {
	*x = CreateRegistryCredentialResponse{}
	mi := &file_deployer_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegistryCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegistryCredentialResponse) ProtoMessage() {}

func (x *CreateRegistryCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegistryCredentialResponse.ProtoReflect.Descriptor instead.
func (*CreateRegistryCredentialResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRegistryCredentialResponse) GetCredential() *RegistryCredentialMetadata {
	if x != nil {
		return x.Credential
	}
	return nil
}

type ListRegistryCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistryCredentialsRequest) Reset() {
	*x = ListRegistryCredentialsRequest{}
	mi := &file_deployer_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistryCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistryCredentialsRequest) ProtoMessage() {}

func (x *ListRegistryCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistryCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListRegistryCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ListRegistryCredentialsRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type ListRegistryCredentialsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Credentials   []*RegistryCredentialMetadata `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistryCredentialsResponse) Reset() {
	*x = ListRegistryCredentialsResponse{}
	mi := &file_deployer_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistryCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistryCredentialsResponse) ProtoMessage() {}

func (x *ListRegistryCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistryCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListRegistryCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *ListRegistryCredentialsResponse) GetCredentials() []*RegistryCredentialMetadata {
	if x != nil {
		return x.Credentials
	}
	return nil
}

var File_deployer_v1_registry_proto protoreflect.FileDescriptor

const file_deployer_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1adeployer/v1/registry.proto\x12\vdeployer.v1\"\xac\x01\n" +
	"\x1fCreateRegistryCredentialRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1a\n" +
	"\bregistry\x18\x03 \x01(\tR\bregistry\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"\x8e\x01\n" +
	"\x1aRegistryCredentialMetadata\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1a\n" +
	"\bregistry\x18\x03 \x01(\tR\bregistry\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"k\n" +
	" CreateRegistryCredentialResponse\x12G\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2'.deployer.v1.RegistryCredentialMetadataR\n" +
	"credential\";\n" +
	"\x1eListRegistryCredentialsRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\"l\n" +
	"\x1fListRegistryCredentialsResponse\x12I\n" +
	"\vcredentials\x18\x01 \x03(\v2'.deployer.v1.RegistryCredentialMetadataR\vcredentials2\x8a\x02\n" +
	"\x19RegistryCredentialService\x12w\n" +
	"\x18CreateRegistryCredential\x12,.deployer.v1.CreateRegistryCredentialRequest\x1a-.deployer.v1.CreateRegistryCredentialResponse\x12t\n" +
	"\x17ListRegistryCredentials\x12+.deployer.v1.ListRegistryCredentialsRequest\x1a,.deployer.v1.ListRegistryCredentialsResponseBPZNgithub.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_registry_proto_rawDescOnce sync.Once
	file_deployer_v1_registry_proto_rawDescData []byte
)

func file_deployer_v1_registry_proto_rawDescGZIP() []byte {
	file_deployer_v1_registry_proto_rawDescOnce.Do(func() {
		file_deployer_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_registry_proto_rawDesc), len(file_deployer_v1_registry_proto_rawDesc)))
	})
	return file_deployer_v1_registry_proto_rawDescData
}

var file_deployer_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_deployer_v1_registry_proto_goTypes = []any{
	(*CreateRegistryCredentialRequest)(nil),  // 0: deployer.v1.CreateRegistryCredentialRequest
	(*RegistryCredentialMetadata)(nil),       // 1: deployer.v1.RegistryCredentialMetadata
	(*CreateRegistryCredentialResponse)(nil), // 2: deployer.v1.CreateRegistryCredentialResponse
	(*ListRegistryCredentialsRequest)(nil),   // 3: deployer.v1.ListRegistryCredentialsRequest
	(*ListRegistryCredentialsResponse)(nil),  // 4: deployer.v1.ListRegistryCredentialsResponse
}
var file_deployer_v1_registry_proto_depIdxs = []int32{
	1, // 0: deployer.v1.CreateRegistryCredentialResponse.credential:type_name -> deployer.v1.RegistryCredentialMetadata
	1, // 1: deployer.v1.ListRegistryCredentialsResponse.credentials:type_name -> deployer.v1.RegistryCredentialMetadata
	0, // 2: deployer.v1.RegistryCredentialService.CreateRegistryCredential:input_type -> deployer.v1.CreateRegistryCredentialRequest
	3, // 3: deployer.v1.RegistryCredentialService.ListRegistryCredentials:input_type -> deployer.v1.ListRegistryCredentialsRequest
	2, // 4: deployer.v1.RegistryCredentialService.CreateRegistryCredential:output_type -> deployer.v1.CreateRegistryCredentialResponse
	4, // 5: deployer.v1.RegistryCredentialService.ListRegistryCredentials:output_type -> deployer.v1.ListRegistryCredentialsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_deployer_v1_registry_proto_init() }
func file_deployer_v1_registry_proto_init() {
	if File_deployer_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_registry_proto_rawDesc), len(file_deployer_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_v1_registry_proto_goTypes,
		DependencyIndexes: file_deployer_v1_registry_proto_depIdxs,
		MessageInfos:      file_deployer_v1_registry_proto_msgTypes,
	}.Build()
	File_deployer_v1_registry_proto = out.File
	file_deployer_v1_registry_proto_goTypes = nil
	file_deployer_v1_registry_proto_depIdxs = nil
}
