// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: deployer/v1/registry.proto

package deployerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryCredentialService_CreateRegistryCredential_FullMethodName = "/deployer.v1.RegistryCredentialService/CreateRegistryCredential"
	RegistryCredentialService_ListRegistryCredentials_FullMethodName  = "/deployer.v1.RegistryCredentialService/ListRegistryCredentials"
)

// RegistryCredentialServiceClient is the client API for RegistryCredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Operator-only, write-only credential management. Rotation creates a new
// immutable revision; retained releases continue using the original revision.
type RegistryCredentialServiceClient interface {
	CreateRegistryCredential(ctx context.Context, in *CreateRegistryCredentialRequest, opts ...grpc.CallOption) (*CreateRegistryCredentialResponse, error)
	ListRegistryCredentials(ctx context.Context, in *ListRegistryCredentialsRequest, opts ...grpc.CallOption) (*ListRegistryCredentialsResponse, error)
}

type registryCredentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryCredentialServiceClient(cc grpc.ClientConnInterface) RegistryCredentialServiceClient {
	return &registryCredentialServiceClient{cc}
}

func (c *registryCredentialServiceClient) CreateRegistryCredential(ctx context.Context, in *CreateRegistryCredentialRequest, opts ...grpc.CallOption) (*CreateRegistryCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRegistryCredentialResponse)
	err := c.cc.Invoke(ctx, RegistryCredentialService_CreateRegistryCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryCredentialServiceClient) ListRegistryCredentials(ctx context.Context, in *ListRegistryCredentialsRequest, opts ...grpc.CallOption) (*ListRegistryCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegistryCredentialsResponse)
	err := c.cc.Invoke(ctx, RegistryCredentialService_ListRegistryCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryCredentialServiceServer is the server API for RegistryCredentialService service.
// All implementations must embed UnimplementedRegistryCredentialServiceServer
// for forward compatibility.
//
// Operator-only, write-only credential management. Rotation creates a new
// immutable revision; retained releases continue using the original revision.
type RegistryCredentialServiceServer interface {
	CreateRegistryCredential(context.Context, *CreateRegistryCredentialRequest) (*CreateRegistryCredentialResponse, error)
	ListRegistryCredentials(context.Context, *ListRegistryCredentialsRequest) (*ListRegistryCredentialsResponse, error)
	mustEmbedUnimplementedRegistryCredentialServiceServer()
}

// UnimplementedRegistryCredentialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryCredentialServiceServer struct{}

func (UnimplementedRegistryCredentialServiceServer) CreateRegistryCredential(context.Context, *CreateRegistryCredentialRequest) (*CreateRegistryCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRegistryCredential not implemented")
}
func (UnimplementedRegistryCredentialServiceServer) ListRegistryCredentials(context.Context, *ListRegistryCredentialsRequest) (*ListRegistryCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRegistryCredentials not implemented")
}
func (UnimplementedRegistryCredentialServiceServer) mustEmbedUnimplementedRegistryCredentialServiceServer() {
}
func (UnimplementedRegistryCredentialServiceServer) testEmbeddedByValue() {}

// UnsafeRegistryCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryCredentialServiceServer will
// result in compilation errors.
type UnsafeRegistryCredentialServiceServer interface {
	mustEmbedUnimplementedRegistryCredentialServiceServer()
}

func RegisterRegistryCredentialServiceServer(s grpc.ServiceRegistrar, srv RegistryCredentialServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistryCredentialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryCredentialService_ServiceDesc, srv)
}

func _RegistryCredentialService_CreateRegistryCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRegistryCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryCredentialServiceServer).CreateRegistryCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryCredentialService_CreateRegistryCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryCredentialServiceServer).CreateRegistryCredential(ctx, req.(*CreateRegistryCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryCredentialService_ListRegistryCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegistryCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryCredentialServiceServer).ListRegistryCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryCredentialService_ListRegistryCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryCredentialServiceServer).ListRegistryCredentials(ctx, req.(*ListRegistryCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryCredentialService_ServiceDesc is the grpc.ServiceDesc for RegistryCredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryCredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployer.v1.RegistryCredentialService",
	HandlerType: (*RegistryCredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRegistryCredential",
			Handler:    _RegistryCredentialService_CreateRegistryCredential_Handler,
		},
		{
			MethodName: "ListRegistryCredentials",
			Handler:    _RegistryCredentialService_ListRegistryCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deployer/v1/registry.proto",
}
