// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: deployer/v1/secret.proto

package deployerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretRequest) Reset() {
	*x = SetSecretRequest{}
	mi := &file_deployer_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretRequest) ProtoMessage() {}

func (x *SetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretRequest.ProtoReflect.Descriptor instead.
func (*SetSecretRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *SetSecretRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *SetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetSecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretResponse) Reset() {
	*x = SetSecretResponse{}
	mi := &file_deployer_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretResponse) ProtoMessage() {}

func (x *SetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretResponse.ProtoReflect.Descriptor instead.
func (*SetSecretResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_secret_proto_rawDescGZIP(), []int{1}
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_deployer_v1_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_secret_proto_rawDescGZIP(), []int{2}
}

func (x *ListSecretsRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_deployer_v1_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_secret_proto_rawDescGZIP(), []int{3}
}

func (x *ListSecretsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_deployer_v1_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_deployer_v1_secret_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSecretRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_deployer_v1_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployer_v1_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_deployer_v1_secret_proto_rawDescGZIP(), []int{5}
}

var File_deployer_v1_secret_proto protoreflect.FileDescriptor

const file_deployer_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x18deployer/v1/secret.proto\x12\vdeployer.v1\"W\n" +
	"\x10SetSecretRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x13\n" +
	"\x11SetSecretResponse\"/\n" +
	"\x12ListSecretsRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\"+\n" +
	"\x13ListSecretsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"D\n" +
	"\x13DeleteSecretRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteSecretResponse2\x82\x02\n" +
	"\rSecretService\x12J\n" +
	"\tSetSecret\x12\x1d.deployer.v1.SetSecretRequest\x1a\x1e.deployer.v1.SetSecretResponse\x12P\n" +
	"\vListSecrets\x12\x1f.deployer.v1.ListSecretsRequest\x1a .deployer.v1.ListSecretsResponse\x12S\n" +
	"\fDeleteSecret\x12 .deployer.v1.DeleteSecretRequest\x1a!.deployer.v1.DeleteSecretResponseBPZNgithub.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1b\x06proto3"

var (
	file_deployer_v1_secret_proto_rawDescOnce sync.Once
	file_deployer_v1_secret_proto_rawDescData []byte
)

func file_deployer_v1_secret_proto_rawDescGZIP() []byte {
	file_deployer_v1_secret_proto_rawDescOnce.Do(func() {
		file_deployer_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deployer_v1_secret_proto_rawDesc), len(file_deployer_v1_secret_proto_rawDesc)))
	})
	return file_deployer_v1_secret_proto_rawDescData
}

var file_deployer_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_deployer_v1_secret_proto_goTypes = []any{
	(*SetSecretRequest)(nil),     // 0: deployer.v1.SetSecretRequest
	(*SetSecretResponse)(nil),    // 1: deployer.v1.SetSecretResponse
	(*ListSecretsRequest)(nil),   // 2: deployer.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 3: deployer.v1.ListSecretsResponse
	(*DeleteSecretRequest)(nil),  // 4: deployer.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 5: deployer.v1.DeleteSecretResponse
}
var file_deployer_v1_secret_proto_depIdxs = []int32{
	0, // 0: deployer.v1.SecretService.SetSecret:input_type -> deployer.v1.SetSecretRequest
	2, // 1: deployer.v1.SecretService.ListSecrets:input_type -> deployer.v1.ListSecretsRequest
	4, // 2: deployer.v1.SecretService.DeleteSecret:input_type -> deployer.v1.DeleteSecretRequest
	1, // 3: deployer.v1.SecretService.SetSecret:output_type -> deployer.v1.SetSecretResponse
	3, // 4: deployer.v1.SecretService.ListSecrets:output_type -> deployer.v1.ListSecretsResponse
	5, // 5: deployer.v1.SecretService.DeleteSecret:output_type -> deployer.v1.DeleteSecretResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deployer_v1_secret_proto_init() }
func file_deployer_v1_secret_proto_init() {
	if File_deployer_v1_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployer_v1_secret_proto_rawDesc), len(file_deployer_v1_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deployer_v1_secret_proto_goTypes,
		DependencyIndexes: file_deployer_v1_secret_proto_depIdxs,
		MessageInfos:      file_deployer_v1_secret_proto_msgTypes,
	}.Build()
	File_deployer_v1_secret_proto = out.File
	file_deployer_v1_secret_proto_goTypes = nil
	file_deployer_v1_secret_proto_depIdxs = nil
}
