syntax = "proto3";

package deployer.v1;

option go_package = "github.com/0xivanov/self-hosted-deployer/internal/proto/deployer/v1;deployerv1";

service SecretService {
  rpc SetSecret(SetSecretRequest) returns (SetSecretResponse);
  rpc ListSecrets(ListSecretsRequest) returns (ListSecretsResponse);
  rpc DeleteSecret(DeleteSecretRequest) returns (DeleteSecretResponse);
}

message SetSecretRequest {
  string app_name = 1;
  string name = 2;
  string value = 3;
}

message SetSecretResponse {}

message ListSecretsRequest {
  string app_name = 1;
}

message ListSecretsResponse {
  repeated string names = 1;
}

message DeleteSecretRequest {
  string app_name = 1;
}

message DeleteSecretResponse {}
